### ISSUE TITLE
Mobile event card resizing

### ISSUE THREAD

**Issue by 12Timur21** [werner-scholtz/kalender#1]
Hi. I really enjoyed working with your package, but I encountered an unpleasant bug while resizing an event on iPhone. 

This can be reproduced as follows:
1. Select the edge of the card.
2. Select the second edge of the card and start resizing.
3. Release the edge of the card from which the stretching was performed.
4. (Problematic) Without releasing the first finger, I try to resize with the second finger, but nothing works.
5. I release the first finger and get an error.

I would be very grateful if you could help me with this issue
![kalender_error](https://github.com/werner-scholtz/kalender/assets/56220668/157617a4-c047-4c3b-8f9b-309b233bbf17)
![Error message](https://github.com/werner-scholtz/kalender/assets/56220668/35f8e158-98dd-4a4d-9faa-8f6f46d50e22)

**Comment by werner-scholtz** [comment]
Hi, can you please send the output of "flutter doctor -v" and what version of the package are you using ?

**Comment by 12Timur21** [comment]
I reproduced the error directly from the example in the GitHub repository

![image](https://github.com/werner-scholtz/kalender/assets/56220668/67c8f210-eccf-4947-9e6e-a58185aa6f74)

**Comment by werner-scholtz** [comment]
Okay, thanks you for letting me know I'll let you know I've fixed it.

**Comment by werner-scholtz** [comment]
Hi, I have pushed some changes that should fix your problem I have also added a section in the read me explaining how rescheduling and resizing works on mobile https://github.com/werner-scholtz/kalender#mobile-rescheduling-resizing 

Let me know if it works.

**Comment by 12Timur21** [comment]
Thank you for the very prompt response, but for some reason I am still encountering an error with your example while resizing on iPhone XR

![image](https://github.com/werner-scholtz/kalender/assets/56220668/d7c87a00-a62f-4c17-894a-51b6c08bcb4d)
![image](https://github.com/werner-scholtz/kalender/assets/56220668/04944f74-4ef2-4a6f-b43b-917f1eb8b8f7)
![image](https://github.com/werner-scholtz/kalender/assets/56220668/7b57de52-343f-4732-96bc-9c068f48cd18)

**Comment by werner-scholtz** [comment]
Okay I have replicated it on android and changed the way it handles multi finger resizing, give it another try and let me know.

**Comment by 12Timur21** [comment]
Hi ). I realized that on Android you can perform resizing with one finger simply by stretching the edge of the card down, but for some reason on iOS this mechanism does not work and when I try to stretch the bottom edge I start moving the card down

In order to somehow resize the card on the iPhone, I had to use two fingers, which apparently sometimes disrupted the package logic, causing the selectedEvent to reset from time to time.

![image](https://github.com/werner-scholtz/kalender/assets/56220668/3c9d1a0e-8407-40d7-8461-09ef05777f7c)
![image](https://github.com/werner-scholtz/kalender/assets/56220668/ebfb80bc-3a48-421c-8d7e-97546efa843d)

**Comment by werner-scholtz** [comment]
It sounds like you are rescheduling the event and resizing it at the same time, I didn't test this thanks for the info I will work on a fix for this.

**Comment by werner-scholtz** [comment]
Hi I have re-worked it a bit so that rescheduling and resizing cannot happen at the same time and resizing only works on a single side at a time, let me know if it works for you now.

**Comment by 12Timur21** [comment]
Hi. I checked the fix and now everything is working perfectly :) Thank you very much for the quick fix and the awesome package!

**Comment by werner-scholtz** [comment]
It's a pleasure
